version: '3.1'

services:
  digital_wallet:
    restart: on-failure
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/digital_wallet
    depends_on: postgres
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
