version: '3.1'

services:
  digital_wallet:
    container_name: digitalWallet
    restart: on-failure
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/digital_wallet
    depends_on:
      - postgres
      - mongo
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "550MB"
  postgres:
    container_name: postgres-wallet
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  mongo:
    image: mongo:7.0.5
    restart: on-failure
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - /data/db:/data/db