services:
    digital_wallet:
        restart: on-failure
        build: .
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "550MB"
    postgres:
        container_name: postgres
        image: postgres
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DATABASE: ${DB_DATABASE}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "550MB"
