version: '3.1'

services:
  digital_wallet:
    restart: on-failure
    build: .
    ports:
     - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/digital_wallet
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
